[package]
name = "conway-life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "5.1.2"
rand = "0.8.5"
softbuffer = "0.3.4"
winit = "0.28.1"
